### PR TITLE
Pull Request: Improved UI for Dark Mode and Light Mode

### PR DESCRIPTION
**Pull request by abhishekkumar35**
Description :
This pull request aims to enhance the UI of the repository's dark mode and light mode by extending the visibility mode to other elements such as input buttons, headings (h3, h1), and dynamically changing the text of buttons based on the UI mode.
Changes made : 
 - Added visibility mode support to input buttons, headings (h3, h1), and other relevant elements.
 - Updated the CSS styles to ensure proper visibility mode styling for the elements.
 - Implemented dynamic text change for buttons to reflect the UI mode.
 Testing :
 Testing
- Tested the improved UI in both dark mode and light mode.
- Verified that the input buttons, headings (h3, h1), and other elements are responsive to the visibility mode.
- Verified that the text of buttons dynamically changes based on the UI mode

### CODE REVIEW

**Review by hanshal101 — CHANGES_REQUESTED** [review]
Hello Abhishek, nice to have to on this repository. I really appreciate you changes you made i would like a few changes :

1) Make a Toggle button to switch in between Dark and Light mode. Place this button on the top right of the page.

2) Make the checkbox-radio button a bit cool looking.

If you can do this for me please leave a comment or I'll merge the changes you made and add these changes in issues section.

Thank You for your contribution.

**Comment by codedevhulk** [comment]
Hi, hanshal, I understoodd your first point, will implement that. but I need more clarification on your second point. 
Can you tell me what changes you want in radio button to make it look more cool?
Thank you.

**Comment by abhishekkumar35** [comment]
Hi, hanshal101, I understood your first point, and implemented button position to top right corner.
but I need more clarification on your second point.
Can you tell me what changes you want in radio button to make it look more cool?
Thank you.

**Comment by hanshal101** [comment]
Hey Abhishek,

- You didn't make a toggle button for the dark mode.
- And about the radio buttons it should look something like this:
  - [Example](https://i.ytimg.com/vi/9UZIv8lyaXA/maxresdefault.jpg). The box should be highlighted. Also make this in vertical format.

**Comment by abhishekkumar35** [comment]
Hi , didnt get your first point. i have already made, and tested toggle button working fine for both mode. 
Thank you for giving reference of ui of radio button.

**Comment by hanshal101** [comment]
Thanks For your contribution Abhishek. I have managed the first task.

**Review by hanshal101 — APPROVED** [review]

**Pull request merged**
